/* CSS Módulo Blog ESLSCA */

var css = 'button.accordion {'
    +'background-color: #006aa4;'
    +'color: #fff;'
    +'cursor: pointer;'
    +'padding: 18px;'
    +'width: 100%;'
    +'border: none;'
    +'text-align: left;'
    +'outline: none;'
    +'font-size: 13px;'
    +'transition: 0.4s;'
    +'padding-right: 42px;'
    +'font-family: "sans-serif";'
	+'}'
	+'button.accordion.active, button.accordion:hover {'
    +'background-color: #ff8f00;'
	+'}'
	+'button.accordion:before {'
    +'content: \'\002B\';'
    +'color: #fff;'
    +'font-weight: bold;'
    +'margin-left: 5px;'
    +'position: absolute;'
    +'right: 25px;'
    +'font-size: 15px;'
	+'}'
	+'button.accordion.active:before {'
    +'content: \'\2212\';'
	+'}'
	+'div.panel {'
    +'padding: 0 18px;'
    +'background-color: #f8f8f8;'
    +'max-height: 0;'
    +'overflow: hidden;'
    +'transition: max-height 0.2s ease-out;'
    +'border-right: 2px solid #ff8f00;'
    +'border-left: 2px solid #ff8f00;'
    +'position: relative;'
	+'}'
	+'.panel:last-child {'
    +'border-bottom: 2px solid #ff8f00;'
	+'}'
	+'.panel-left {'
    +'width: 60%;'
    +'float: left;'
    +'padding-bottom: 40px;'
    +'padding-top: 18px;'
    +'background: #f8f8f8;'
	+'}'
	+'.panel-left p{'
	+'margin: 0px;'
    +'padding: 0px;'
    +'padding-right: 18px;'
	+'}'
	+'.panel-right {'
    +'width: 40%;'
    +'float: right;'
    +'height: 100%;'
    +'position: absolute;'
    +'right: 0px;'
    +'background: #fff;'
	+'}'
	+'.panel-right img {'
    +'width: auto;'
    +'height: auto;'
    +'margin: auto;'
    +'display: block;'
    +'vertical-align: middle;'
    +'max-width: 225px;'
    +'max-height: 225px;'
    +'position: absolute;'
    +'top: 0;'
    +'left: 0;'
    +'right: 0;'
    +'bottom: 0;'
	+'}'
	+'.lireplus {'
    +'background: #ffffff;'
    +'color: #006aa4;'
    +'text-decoration: none;'
    +'padding: 4px 8px 6px 8px;'
    +'cursor: pointer;'
    +'border: 1px solid #006aa4;'
    +'border-radius: 35px;'
    +'font-size: 13px;'
    +'position: relative;'
    +'bottom: -20px;'
    +'transition: .4s;'
	+'}'
	+'.lireplus:hover {'
    +'color: #ff8f00'
	+'}'

	;
console.log("cargando css blog");
head = document.head || document.getElementsByTagName('head')[0];
style = document.createElement('style');

style.type = 'text/css';
if (style.styleSheet){
  style.styleSheet.cssText = css;
} else {
  style.appendChild(document.createTextNode(css));
}

head.appendChild(style);
